version: "3.9"
services: 
  djangoprueba:
    build: .
    ports:
      - '8000:8000'
    links:
      - postgresql
  postgresql: 
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER = peppa
      - POSTGRES_PASSWORD = postgres
